service:
  name: lambda-function
  identifier: lambdafunction
  serviceDefinition:
    type: AwsLambda
    spec:
      manifests:
        - manifest:
            identifier: lambdasample
            type: AwsLambdaFunctionDefinition
            spec:
              store:
                type: Harness
                spec:
                  files:
                    - /lambdaFunctions/lambda_func_hello_world
      artifacts:
        primary:
          primaryArtifactRef: <+input>
          sources:
            - spec:
                connectorRef: your-aws-connector
                bucketName: your-bucket-name
                region: your_aws_region
                filePath: lambda-functions/hello_world.zip
              identifier: awslambda
              type: AmazonS3
  gitOpsEnabled: false
  orgIdentifier: your_org_id
  projectIdentifier: your_project_id
